name: Build and deploy ASP.Net Core app to Azure Web App - registrationpeopleapi

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restaurar pacotes
        run: dotnet restore RegistrationPeopleApi/RegistrationPeople.API/RegistrationPeople.API.csproj

      - name: Build
        run: dotnet build RegistrationPeopleApi/RegistrationPeople.API/RegistrationPeople.API.csproj --configuration Release --no-restore

      - name: Publicar
        run: dotnet publish RegistrationPeopleApi/RegistrationPeople.API/RegistrationPeople.API.csproj -c Release -o published --no-build

      - name: Upload do artefato
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-app
          path: published

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download do artefato
        uses: actions/download-artifact@v4
        with:
          name: dotnet-app

      - name: Login no Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4D623389CB2E44A3863BAC7CC28550B7 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_BCF524ADA1B64EFF9B104B67B2ECAA2C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_5A6CEEBBD08C4030BC01D5DBA823F16F }}

      - name: Deploy no Azure App Service
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'registrationpeopleapi'
          slot-name: 'Production'
          package: .
